### ISSUE TITLE
Wrong response when POSTing a new link

### ISSUE THREAD

**Issue by grmmph** [BranchMetrics/branch-deep-linking-public-api#16]
We have a custom domain configured in our dashboard. We've tested it with marketing links generated via branch's UI.

The problem is, that when trying to generating a link via `POST`ing to `url` endpoint, the response received is `xxx.app.link` and not our pretty custom domain.

But wait, It's getting weirder!
The `app.link` prefix we get is inconsistent to the `app.link` configured in our dashboard, while the whole `app.link` thing is inconsistent with the fact our app still uses the old `bnc.lt`.

For example:
- In dashboard's link settings, under "Custom Link Domain" We've got a disabled input field with the value `bnc.li`
- Underneath we've configured our own domain `awesome.domain`
- Our app.ink prefix is (e.g.) `abcd`, at least according to the note under the `SHA256 Cert Fingerprints` input field.
- When creating marketing links via branch dashboard, the link format would be `awesome.domain/awesome-link`
- When our app received a url from WhatsApp, we get `bnc.lt/random-link-id`
- When generating link via branch API (or `branch.link(options)`), the response is `wxyz.app.link/alias-or-random-id` but not `awesome.domain/alias-or-random-id` as expected.
- Assigning `type: 2` doesn't create a marketing link as documented.

So sometime branch.io uses the `bnc.lt`, sometime it uses our custom domain and sometimes it uses `app.link` with a (probably) wrong prefix.

Not very inconsistent I'd say :)
Nevertheless, the breaking issue here for me is that I'm not able to generate custom-domain links programmatically.

Thanks a good day!

**Comment by grmmph** [comment]
Ok, seems like the main issue caused because of confusion with the branch api live and test keys.

But still it could be improved:
- unifying links
- type: 2 doesn't add links to marketing table

**Comment by aaustin** [comment]
Hey @grmmph - I'm super sorry that you went through this torture. Key mixups are unfortunately all too common. We added that system to help companies better segment their test data from live data, but it seems like it sometimes adds more pain than benefit.

On your suggestions, we worry about unifying links between the two accounts, because it allows potentially bad behavior where people launch with the incorrect keys and can use them interchangeably. It's one of the reasons that we now create all links with `test-app.link` on the test account, to help prevent this confusion.

On type:2 not creating a marketing link, I just checked that this should still be working. Can you make sure you're passing it as an integer and not a string? I thought we handle both but it's possible that's not the case.

**Comment by grmmph** [comment]
Thanks for quick reply @aaustin!

Indeed using the test key was a stupidity on my side. But Actually, I didn't get `xxx.test-app.link` as you suggested, but the `xxx.app.link` - maybe if I would have get the `test-app` response I would realize much faster I'm using a wrong key. Maybe something to improve on your side?

Yes, `type: 2` was passed as integer at the root of the params object (not an attribute of `data`)

**Comment by aaustin** [comment]
Hey @grmmph - I just tried this curl for a test app I have:
`curl -X POST -H "Content-Type: application/json" -d '{"channel":"test","campaign":"test123","type":2,"data":"{\"$always_deeplink\":false}","branch_key":"key_live_gpk6Xg4wInPq1IYbxwG4akjhqDc7bplS"}' https://api.branch.io/v1/url`

Upon reloading the marketing page, the link appeared. Can you send over an example request you make where this doesn't happen? I can help dig in there.

**Comment by aaustin** [comment]
Going to close the issue for now.
